# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_binlog_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binlog_datetime',
            old_name='binlog_pos',
            new_name='end_pos',
        ),
        migrations.AddField(
            model_name='binlog_datetime',
            name='start_pos',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
