# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkrs', '0006_backuplog_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuphostconf',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
