# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkrs', '0008_auto_20180307_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuplog',
            name='change_master_to',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
